version: "3"

services:
  octprint-alpine:
    build:
      context: .
      args:
        octoprint_ref: 1.5.2
    environment:
      LD_LIBRARY_PATH: /opt/vc/lib
    ports:
      - "5000:5000"
    volumes: 
      - "octoprint:/home/octoprint"
      - "/opt/vc:/opt/vc:ro"
    devices:
    - "/dev/vchiq:/dev/vchiq:ro"

volumes:
  octoprint:
