---
version: "3.7"
services:
  traefik:
    image: traefik:v2.4
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.print.3d`)"
      - "traefik.http.routers.traefik.entryPoints=web"
      - "traefik.http.services.traefik.loadBalancer.server.port=8080"
      - "traefik.http.routers.traefik.service=api@internal"
    ports:
      - published: 80
        target: 80
        protocol: tcp
        mode: host
      - published: 443
        target: 443
        protocol: tcp
        mode: host
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/:/etc/traefik:ro
    environment:
      - TZ=America/Recife
    deploy:
      mode: global

networks:
  proxy:
    driver: overlay
    attachable: true
