---
version: "3.7"
services:
  traefik:
    image: traefik:v2.4
    ports:
      - published: 80
        target: 80
        protocol: tcp
        mode: host
      - published: 443
        target: 443
        protocol: tcp
        mode: host
      - published: 8080
        target: 8080
        protocol: tcp
        mode: host
    networks:
      - public
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - --api
      - --api.dashboard=true
      - --api.dashboard.insecure=true
      - --providers.docker=true
      - --providers.docker.watch=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=traefik_public
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.websecure.address=:443
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.print.3d`)"
      - "traefik.http.routers.traefik.entryPoints=web,websecure"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.services.traefik.loadBalancer.server.port=8080"
    environment:
      TZ: America/Recife
    healthcheck:
      test: ["CMD", "traefik", "healthcheck"]
      timeout: 30s
      interval: 10s
      retries: 5

networks:
  public:
    attachable: true
