---
global:
  checkNewVersion: true

providers:
  docker:
    endpoint: "http://tasks.socket:2375"
    swarmMode: true
    exposedbydefault: false
    network: traefik_public
    watch: true
  file:
    directory: /etc/traefik/config
    watch: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"

api:
  dashboard: true

accessLog:
  fields:
    names:
      StartUTC: drop

ping: {}

metrics:
  prometheus: {}
