---
tls:
  stores:
    default: {}
  certificates:
    - certFile: /certs/print.3d.crt
      keyFile: /certs/print.3d.key
  options:
    default:
      minVersion: VersionTLS13
      sniStrict: true
    tls12:
      minVersion: true
      sniStrict: true
      cipherSuites: {
      "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",
      "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
      "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
      "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
      "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305",
      "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305"
      }

http:
  middlewares:
    admin-auth:
      basicAuth:
        users:
          - "admin:$apr1$1994uKAy$B/qWqePYtrQhtuXITYTml0"
  routers:
    octoprint:
      entryPoints:
        - web
        - websecure
      service: octoprint
      rule: "Host(`print.3d`)"
      tls: {}
    mjpg:
      entryPoints:
        - web
        - websecure
      service: mjpg
      rule: "Host(`cam.print.3d`)"
      tls: {}

  services:
    octoprint:
      loadBalancer:
        servers:
          - url: http://octoprint:5000
        passHostHeader: true
    mjpg:
      loadBalancer:
        servers:
          - url: http://mjpg-streamer:8080
        passHostHeader: true
