name: Build Images

on:
  push:
    branches:
      - master

jobs:
  filters:
    runs-on: ubuntu-latest
    outputs:
      alpine: docker_build_alpine
    steps:
      - 
        uses: actions/checkout@v2
      - 
        uses: dorny/paths-filter@v2.6.0
        id: filter
        with:
          filters: '.github/filters.yml'

  docker_build_alpine:
    runs-on: ubuntu-latest
    needs: filters
    if: ${{ needs.filters.outputs.alpine == 'true' }}
    steps:
      - 
        uses: actions/checkout@v2
      - 
        name: Get OctoPrint Stable
        id: latest-octoprint
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: OctoPrint
          repo: OctoPrint
          excludes: prerelease,draft
      - 
        name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          platforms: arm,arm64
      -
        name: Set up Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ hashfiles('**/Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - 
        name: Run a Test Build
        id: build
        uses: docker/build-push-action@v2
        with:
          push: false
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max
          platforms: |
            linux/amd64
            linux/arm/v7
            linux/arm64
          build-args: |
            octoprint_ref=${{ steps.latest-octoprint.outputs.release }}